name: Build Local-github (All targets with full dropdowns)

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: "Build target"
        options:
          - pi
          - pc
          - arm64
          - armhf
          - riscv64
          - i386
          - i860
        default: pi
      hostname:
        description: "Hostname"
        default: local-github
      username:
        description: "Console username"
        default: chip
      user_password:
        description: "User password"
        default: raspberry
      root_password:
        description: "Root password"
        default: root
      wifi_ssid:
        description: "Wi‑Fi SSID"
        default: YourWiFi
      wifi_password:
        description: "Wi‑Fi password"
        default: YourPassword
      wifi_country:
        type: choice
        description: "Wi‑Fi country code (ISO 3166‑1 alpha‑2)"
        options:
          - AF
          - AX
          - AL
          - DZ
          - AS
          - AD
          - AO
          - AI
          - AQ
          - AG
          - AR
          - AM
          - AW
          - AU
          - AT
          - AZ
          - BS
          - BH
          - BD
          - BB
          - BY
          - BE
          - BZ
          - BJ
          - BM
          - BT
          - BO
          - BQ
          - BA
          - BW
          - BV
          - BR
          - IO
          - BN
          - BG
          - BF
          - BI
          - CV
          - KH
          - CM
          - CA
          - KY
          - CF
          - TD
          - CL
          - CN
          - CX
          - CC
          - CO
          - KM
          - CG
          - CD
          - CK
          - CR
          - CI
          - HR
          - CU
          - CW
          - CY
          - CZ
          - DK
          - DJ
          - DM
          - DO
          - EC
          - EG
          - SV
          - GQ
          - ER
          - EE
          - SZ
          - ET
          - FK
          - FO
          - FJ
          - FI
          - FR
          - GF
          - PF
          - TF
          - GA
          - GM
          - GE
          - DE
          - GH
          - GI
          - GR
          - GL
          - GD
          - GP
          - GU
          - GT
          - GG
          - GN
          - GW
          - GY
          - HT
          - HM
          - VA
          - HN
          - HK
          - HU
          - IS
          - IN
          - ID
          - IR
          - IQ
          - IE
          - IM
          - IL
          - IT
          - JM
          - JP
          - JE
          - JO
          - KZ
          - KE
          - KI
          - KP
          - KR
          - KW
          - KG
          - LA
          - LV
          - LB
          - LS
          - LR
          - LY
          - LI
          - LT
          - LU
          - MO
          - MG
          - MW
          - MY
          - MV
          - ML
          - MT
          - MH
          - MQ
          - MR
          - MU
          - YT
          - MX
          - FM
          - MD
          - MC
          - MN
          - ME
          - MS
          - MA
          - MZ
          - MM
          - NA
          - NR
          - NP
          - NL
          - NC
          - NZ
          - NI
          - NE
          - NG
          - NU
          - NF
          - MK
          - MP
          - NO
          - OM
          - PK
          - PW
          - PS
          - PA
          - PG
          - PY
          - PE
          - PH
          - PN
          - PL
          - PT
          - PR
          - QA
          - RE
          - RO
          - RU
          - RW
          - BL
          - SH
          - KN
          - LC
          - MF
          - PM
          - VC
          - WS
          - SM
          - ST
          - SA
          - SN
          - RS
          - SC
          - SL
          - SG
          - SX
          - SK
          - SI
          - SB
          - SO
          - ZA
          - GS
          - SS
          - ES
          - LK
          - SD
          - SR
          - SJ
          - SE
          - CH
          - SY
          - TW
          - TJ
          - TZ
          - TH
          - TL
          - TG
          - TK
          - TO
          - TT
          - TN
          - TR
          - TM
          - TC
          - TV
          - UG
          - UA
          - AE
          - GB
          - US
          - UM
          - UY
          - UZ
          - VU
          - VE
          - VN
          - VG
          - VI
          - WF
          - EH
          - YE
          - ZM
          - ZW
        default: AU
      timezone:
        description: "Timezone (e.g., Australia/Sydney)"
        default: Australia/Sydney
      keyboard:
        type: choice
        description: "Keyboard layout (XKB)"
        options:
          - us
          - gb
          - au
          - de
          - fr
          - es
          - it
          - jp
          - ru
          - br
          - pt
          - pl
          - se
          - no
          - dk
          - fi
          - tr
          - cz
          - sk
          - hu
          - ro
          - gr
          - nl
          - be
          - ch
          - ca
          - mx
          - ua
          - il
          - ar
          - bg
          - lt
          - lv
          - ee
          - hr
          - rs
          - si
          - mk
          - ba
          - is
          - ie
          - in
          - pk
          - bd
          - th
          - vn
          - kr
          - cn
          - tw
          - hk
          - za
          - ir
          - sy
          - kz
          - kg
          - uz
          - tn
          - ma
          - dz
          - eg
          - sa
          - ae
          - qa
          - kw
          - om
          - bh
          - lb
          - jo
          - ps
          - iq
          - ye
          - np
          - lk
          - ph
          - my
          - sg
          - id
          - au_mac
          - us_intl
          - colemak
          - dvorak
          - workman
          - neo
          - bepo
          - custom
        default: au
      keyboard_custom:
        description: "If keyboard=custom, set layout here"
        default: us
      static_ip:
        description: "Static IPv4 (eth0)"
        default: 192.168.1.50
      gateway:
        description: "Gateway IPv4"
        default: 192.168.1.1
      dns:
        description: "DNS servers (semicolon-separated)"
        default: 1.1.1.1;8.8.8.8
      permit_root_login:
        type: choice
        description: "SSH: PermitRootLogin"
        options: [yes, prohibit-password, no]
        default: yes
      password_auth:
        type: choice
        description: "SSH: PasswordAuthentication"
        options: [yes, no]
        default: yes
      pubkey_auth:
        type: choice
        description: "SSH: PubkeyAuthentication"
        options: [yes, no]
        default: yes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare configs from inputs
        env:
          HOSTNAME: ${ github.event.inputs.hostname }
          USERNAME: ${ github.event.inputs.username }
          USERPASS: ${ github.event.inputs.user_password }
          ROOTPASS: ${ github.event.inputs.root_password }
          WIFI_SSID: ${ github.event.inputs.wifi_ssid }
          WIFI_PASSWORD: ${ github.event.inputs.wifi_password }
          WIFI_COUNTRY: ${ github.event.inputs.wifi_country }
          TIMEZONE: ${ github.event.inputs.timezone }
          KEYBOARD: ${ github.event.inputs.keyboard }
          KEYBOARD_CUSTOM: ${ github.event.inputs.keyboard_custom }
          STATIC_IP: ${ github.event.inputs.static_ip }
          GATEWAY: ${ github.event.inputs.gateway }
          DNS: ${ github.event.inputs.dns }
          PERMIT_ROOT_LOGIN: ${ github.event.inputs.permit_root_login }
          PASSWORD_AUTH: ${ github.event.inputs.password_auth }
          PUBKEY_AUTH: ${ github.event.inputs.pubkey_auth }
        run: |
          set -e
          mkdir -p targets/live-build/config/includes.chroot/tmp/payload
          rsync -a shared/ targets/live-build/config/includes.chroot/tmp/payload/
          rsync -a shared/ targets/pi-gen/stage4/05-chip-base/files/

          # If keyboard=custom, override
          if [ "${ github.event.inputs.keyboard }" = "custom" ]; then
            KEYBOARD_VAL="${ github.event.inputs.keyboard_custom }"
          else
            KEYBOARD_VAL="${ github.event.inputs.keyboard }"
          fi

          # Substitute placeholders in templates
          find . -type f \( -path './shared/*' -o -path './targets/*' \) -exec sed -i             -e "s/__HOSTNAME__/${ github.event.inputs.hostname }/g"             -e "s/__USERNAME__/${ github.event.inputs.username }/g"             -e "s/__USERPASS__/${ github.event.inputs.user_password }/g"             -e "s/__ROOTPASS__/${ github.event.inputs.root_password }/g"             -e "s/__WIFI_SSID__/${ github.event.inputs.wifi_ssid }/g"             -e "s/__WIFI_PASSWORD__/${ github.event.inputs.wifi_password }/g"             -e "s/__WIFI_COUNTRY__/${ github.event.inputs.wifi_country }/g"             -e "s#__TIMEZONE__#${ github.event.inputs.timezone }#g"             -e "s/__KEYBOARD__/${ github.event.inputs.keyboard }/g"             -e "s/__KEYBOARD_VAL__/${ github.event.inputs.keyboard_custom }/g"             -e "s/__STATIC_IP__/${ github.event.inputs.static_ip }/g"             -e "s/__GATEWAY__/${ github.event.inputs.gateway }/g"             -e "s/__DNS__/${ github.event.inputs.dns }/g"             -e "s/__PERMIT_ROOT_LOGIN__/${ github.event.inputs.permit_root_login }/g"             -e "s/__PASSWORD_AUTH__/${ github.event.inputs.password_auth }/g"             -e "s/__PUBKEY_AUTH__/${ github.event.inputs.pubkey_auth }/g"             -e "s/__USERNAME__COLON__/${ github.event.inputs.username }:/g"             {} +

      - name: Build Raspberry Pi (pi)
        if: ${ github.event.inputs.target == 'pi' }
        uses: usimd/pi-gen-action@v1
        with:
          release: bookworm
          image_name: Local-github
          enable_ssh: true
          stage_list: "stage0 stage1 stage2 stage4"
          deploy_compression: xz
          deploy_compression_level: 9
          deploy_zip: true

      - name: Upload Pi artifact
        if: ${ github.event.inputs.target == 'pi' }
        uses: actions/upload-artifact@v4
        with:
          name: Local-github-pi-arm64
          path: deploy/*

      - name: Build PC ISO (live-build)
        if: ${ github.event.inputs.target == 'pc' }
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build debootstrap syslinux isolinux
          cd targets/live-build
          lb config --architecture amd64 --distribution bookworm --mode debian             --binary-images iso-hybrid --debian-installer live --apt-recommends false
          sudo lb build

      - name: Upload PC artifact
        if: ${ github.event.inputs.target == 'pc' }
        uses: actions/upload-artifact@v4
        with:
          name: Local-github-pc-amd64
          path: targets/live-build/live-image-amd64.hybrid.iso

      - name: Generic/i860 placeholders
        if: ${ github.event.inputs.target != 'pi' && github.event.inputs.target != 'pc' }
        run: |
          echo "Generic or i860 builds are placeholders in this package."
          exit 0
