name: Build Local-github (Final)

on:
  workflow_dispatch:
    inputs:
      target_bits:
        type: choice
        description: "Build target + bitness"
        options:
          - pi 64bit
          - pi 32bit
          - pc 64bit
          - pc 32bit
          - arm64 64bit
          - armhf 32bit
          - riscv64 64bit
          - i386 32bit
          - i860 32bit
        default: pi 64bit

      user_creds:
        type: choice
        description: "Console username:password"
        options:
          - User:password
          - AirysDark:Zombie1986X2
          - chip:raspberry
        default: AirysDark:Zombie1986X2

      wifi_creds:
        type: choice
        description: "Wi-Fi SSID:password"
        options:
          - WI-FI SSID:password
          - Raspbain:Zombie1986X2
          - YourWiFi:YourPassword
        default: Raspbain:Zombie1986X2

      ssh_options:
        type: choice
        description: "SSH options (PermitRootLogin:PasswordAuth:PubkeyAuth)"
        options:
          - true:true:true
          - prohibit-password:true:true
          - false:true:true
          - true:false:true
          - false:false:true
          - true:true:false
        default: true:true:true

      net_ipv4:
        type: choice
        description: "Static IPv4:Gateway:DNS(semicolon-separated)"
        options:
          - 192.168.0.8:192.168.0.1:1.1.1.1;8.8.8.8
          - 192.168.1.50:192.168.1.1:1.1.1.1;8.8.8.8
          - 10.0.0.50:10.0.0.1:9.9.9.9;1.1.1.1
        default: 192.168.0.8:192.168.0.1:1.1.1.1;8.8.8.8

      wifi_country:
        description: "Wi-Fi country (ISO 3166-1 alpha-2)"
        default: AU

      timezone:
        description: "Timezone (IANA tzdb)"
        default: Australia/Sydney

      keyboard:
        description: "Keyboard layout (XKB)"
        default: us

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse target+bitness
        id: tgt
        shell: bash
        run: |
          SEL='${{ github.event.inputs.target_bits }}'
          TARGET="${SEL% *}"
          BIT="${SEL##* }"
          echo "target=$TARGET" >> "$GITHUB_OUTPUT"
          echo "bit_type=$BIT"  >> "$GITHUB_OUTPUT"
          echo "Selected: target=$TARGET bit_type=$BIT"

      - name: Compute architectures
        id: arch
        shell: bash
        run: |
          BIT="${{ steps.tgt.outputs.bit_type }}"
          PI="arm64"; PC="amd64"; GENERIC="arm64"
          if [ "$BIT" = "32bit" ]; then PI="armhf"; PC="i386"; GENERIC="i386"; fi
          echo "pi=$PI" >> "$GITHUB_OUTPUT"
          echo "pc=$PC" >> "$GITHUB_OUTPUT"
          echo "generic=$GENERIC" >> "$GITHUB_OUTPUT"
          echo "Resolved: pi=$PI pc=$PC generic=$GENERIC"

      - name: Example pi job
        if: ${{ steps.tgt.outputs.target == 'pi' }}
        run: echo "Building Pi for ${{ steps.arch.outputs.pi }}"

      - name: Example pc job
        if: ${{ steps.tgt.outputs.target == 'pc' }}
        run: echo "Building PC for ${{ steps.arch.outputs.pc }}"

      - name: Example generic job
        if: ${{ contains(fromJSON('["arm64","armhf","riscv64","i386"]'), steps.tgt.outputs.target) }}
        run: echo "Generic build ${{ steps.tgt.outputs.target }} => ${{ steps.arch.outputs.generic }}"

      - name: Example i860 job
        if: ${{ steps.tgt.outputs.target == 'i860' }}
        run: echo "i860 placeholder"
