name: Build Local-github (Pi via JSON presets)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dummy step
        run: echo "This would parse config/options.json and build image"
